version: "3.9"
services:
  chat-server:
    build: ./server
    ports:
      - "3333:3333"
    links:
      - broker
    environment:
      - BROKER_ENABLED=true
      - BROKER_HOST=broker
  broker:
    build: ./broker
    ports:
      - "61613:61613"